Updates and features
rushitote/slick-chat pull request #40
Opened 2022-07-28 15:52 UTC by varun-s22

In this PR, I have updated notifications display. We are now using `react-toastify` instead of old `notifContext`. 
Updated Login page, to show error when invalid credentials are entered.

Added two new APIs in front-end, i.e `getUserInfo` and `getRoomInfo`, which fetches details of users and rooms respectively. 

Improved LeftPane and ChatWindows components, where the option of Leave Room is now not available for the room owner, and displaying of other details like Room Title, Room Owner .etc can be seen

I'll be adding more on ChatWindows, and shall be working on React Routers(client side rendering), in a different PR.

2022-07-28 21:15 UTC, TheTrio requested changes

2022-07-28 21:15 UTC, TheTrio commented on front-end/src/components/Other/ShowInvite.tsx
> +      toast(`You've joined ${props.roomName}`)
This prop is hardcoded in `front-end/src/Pages/Groups.tsx`. Use the actual room name instead

2022-07-28 21:15 UTC, TheTrio commented on front-end/src/components/Chat/ChatWindow.module.css
> +  position: relative;
Why is this needed?

2022-07-28 21:15 UTC, TheTrio commented on front-end/src/components/Chat/ChatWindow.module.css
> +  background-color: #232526;
The standard colors(including this) are already defined in `front-end/src/App.css`. Use that instead

2022-07-28 21:15 UTC, TheTrio commented on front-end/src/components/Chat/ChatWindow.tsx
> +  const [roomMemberCount, setRoomMemberCount] = useState<number>(0)
Where is this being used?

2022-07-28 21:15 UTC, TheTrio commented on front-end/src/components/LeftPane/Users/LeftPane.tsx
> +        <li key={Math.random()}>
This key isn't needed

2022-07-28 21:15 UTC, TheTrio commented on front-end/src/components/LeftPane/Users/LeftPane.tsx
> +      )}
You can replace the ternary with `&&` since nothing is being rendered in the else part anyway

2022-07-28 21:15 UTC, TheTrio commented on front-end/src/utils/Rooms.ts
> +}
This entire file is not formatted correctly.

2022-07-29 11:01 UTC, varun-s22 commented
I've updated and refactored code, as per your reviews.
It seems like one of the file as some conflicts to resolve, I'll leave that to you :)

2022-07-29 13:49 UTC, merged